# Whatsar — Windows Installer (PowerShell)
# Usage (run as Administrator):
#   irm https://raw.githubusercontent.com/arifianilhamnrr/whatsar/main/install.ps1 | iex
#   .\install.ps1 -Port 8080

#Requires -RunAsAdministrator

param(
    [int]$Port = 8080,
    [string]$Version = "latest",
    [string]$InstallDir = "C:\whatsar",
    [string]$Repo = "arifianilhamnrr/whatsar",
    [switch]$WithTunnel,
    [switch]$NoService
)

$ErrorActionPreference = "Stop"

function Write-Info  { param($msg) Write-Host "[INFO]  $msg" -ForegroundColor Cyan }
function Write-Ok    { param($msg) Write-Host "[OK]    $msg" -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Err   { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }

function Get-Arch {
    if ([Environment]::Is64BitOperatingSystem) {
        if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { return "arm64" }
        return "amd64"
    }
    Write-Err "Butuh Windows 64-bit"
}

function Get-LatestVersion {
    $uri = "https://api.github.com/repos/$Repo/releases/latest"
    $release = Invoke-RestMethod -Uri $uri -Headers @{ "User-Agent" = "whatsar-installer" }
    return $release.tag_name
}

function Get-AssetName {
    param([string]$Ver, [string]$Os, [string]$Arch)
    $verNum = $Ver -replace '^v', ''
    return "whatsar_${verNum}_${Os}_${Arch}"
}

function Install-Binary {
    param([string]$Ver, [string]$Arch)

    $asset = Get-AssetName -Ver $Ver -Os "windows" -Arch $Arch
    $url = "https://github.com/$Repo/releases/download/$Ver/${asset}.zip"

    Write-Info "Download whatsar $Ver ($Arch)..."
    Write-Info "URL: $url"

    $tmp = Join-Path $env:TEMP "whatsar-install"
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    $zip = Join-Path $tmp "whatsar.zip"

    try {
        Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
    } catch {
        Write-Err "Download gagal. Release $Ver untuk windows/$Arch belum ada — buat tag v* di GitHub dulu"
    }

    Expand-Archive -Path $zip -DestinationPath $tmp -Force
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    Copy-Item (Join-Path $tmp "whatsar.exe") (Join-Path $InstallDir "whatsar.exe") -Force
    Remove-Item $tmp -Recurse -Force

    Write-Ok "Binary -> $InstallDir\whatsar.exe"
}

function New-RandomHex {
    param([int]$Bytes = 32)
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLower()
}

function New-EnvFile {
    $apiKey    = New-RandomHex 32
    $adminPass = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 16 | ForEach-Object { [char]$_ })

    $dataDir = Join-Path $InstallDir "data"
    $logsDir = Join-Path $InstallDir "logs"
    @($dataDir, $logsDir) | ForEach-Object { New-Item -ItemType Directory -Force -Path $_ | Out-Null }

    $envPath  = Join-Path $InstallDir ".env"
    $credPath = Join-Path $InstallDir ".credentials"

    if (Test-Path $envPath) {
        Write-Warn ".env sudah ada, skip generate"
        return @{ ApiKey = ""; AdminPass = "" }
    }

    $dbPath = ($dataDir -replace '\\', '/') + "/whatsar.db"
    @"
# Whatsar — generated by install.ps1
WHATSAR_HOST=127.0.0.1
WHATSAR_PORT=$Port
WHATSAR_DB_PATH=$dbPath
WHATSAR_API_KEY=$apiKey
WHATSAR_ADMIN_PASSWORD=$adminPass
WHATSAR_MAX_SESSIONS=2
WHATSAR_LOG_LEVEL=info
# WHATSAR_PUBLIC_URL=https://whatsar.example.com
"@ | Set-Content -Path $envPath -Encoding ASCII

    @"
API_KEY=$apiKey
ADMIN_PASSWORD=$adminPass
"@ | Set-Content -Path $credPath -Encoding ASCII

    Write-Ok ".env -> $envPath"
    return @{ ApiKey = $apiKey; AdminPass = $adminPass }
}

function New-StartWrapper {
    $wrapper = Join-Path $InstallDir "start-whatsar.cmd"
    @"
@echo off
cd /d "$InstallDir"
set WHATSAR_ENV_FILE=$InstallDir\.env
"$InstallDir\whatsar.exe"
"@ | Set-Content -Path $wrapper -Encoding ASCII
    return $wrapper
}

function Install-Service {
    param([string]$Wrapper)

    $svcName = "Whatsar"

    if ($NoService) {
        Write-Warn "Skip Windows Service — jalankan: $Wrapper"
        return
    }

    $existing = Get-Service -Name $svcName -ErrorAction SilentlyContinue
    if ($existing) {
        Stop-Service $svcName -Force -ErrorAction SilentlyContinue
        sc.exe delete $svcName | Out-Null
        Start-Sleep -Seconds 2
    }

    sc.exe create $svcName binPath= "cmd /c `"$Wrapper`"" start= auto DisplayName= "Whatsar WhatsApp API" | Out-Null
    sc.exe description $svcName "Self-hosted WhatsApp API gateway" | Out-Null
    Start-Service $svcName
    Write-Ok "Windows Service '$svcName' aktif"
}

function Install-Cloudflared {
    if (-not $WithTunnel) { return }

    Write-Info "Install Cloudflare Tunnel..."
    if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
        $arch = if ((Get-Arch) -eq "arm64") { "arm64" } else { "amd64" }
        $url  = "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-$arch.exe"
        Invoke-WebRequest -Uri $url -OutFile "C:\Windows\System32\cloudflared.exe" -UseBasicParsing
    }
    Write-Warn "Setup tunnel: cloudflared tunnel login"
    Write-Warn "Jalankan: cloudflared tunnel --no-autoupdate run --token YOUR_TOKEN"
}

# ─── Main ─────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "Whatsar Installer (Windows)" -ForegroundColor Blue
Write-Host ""

$arch = Get-Arch
Write-Info "Arch: $arch"
Write-Info "Install dir: $InstallDir"

$ver = if ($Version -eq "latest") { Get-LatestVersion } else { $Version }
Install-Binary -Ver $ver -Arch $arch
$creds = New-EnvFile
$wrapper = New-StartWrapper
Install-Service -Wrapper $wrapper
Install-Cloudflared

Write-Host ""
Write-Host "Whatsar berhasil terinstall!" -ForegroundColor Green
Write-Host ""
Write-Host "  URL lokal  : http://127.0.0.1:$Port"
Write-Host "  Admin UI   : http://127.0.0.1:$Port/admin"
Write-Host "  API base   : http://127.0.0.1:$Port/api/v1"
Write-Host "  Health     : http://127.0.0.1:$Port/health"
Write-Host ""
if ($creds.ApiKey) {
    Write-Host "  API Key    : $($creds.ApiKey)"
    Write-Host "  Admin pass : $($creds.AdminPass)"
    Write-Host ""
}
Write-Host "  Service    : Get-Service Whatsar"
Write-Host "  Manual run : $wrapper"
Write-Host ""
Write-Warn "Simpan API Key dan admin password — tidak ditampilkan lagi!"
Write-Host ""