# Whatsar — Windows Installer (PowerShell)
# Usage (run as Administrator):
#   irm https://raw.githubusercontent.com/<user>/whatsar/main/install.ps1 | iex
#   .\install.ps1 -Port 8080
#
# Requires: Windows 10/11 or Windows Server 2019+

#Requires -RunAsAdministrator

param(
    [int]$Port = 8080,
    [string]$Version = "latest",
    [string]$InstallDir = "C:\whatsar",
    [string]$Repo = "whatsar/whatsar",
    [switch]$WithTunnel,
    [switch]$NoService
)

$ErrorActionPreference = "Stop"

function Write-Info  { param($msg) Write-Host "[INFO]  $msg" -ForegroundColor Cyan }
function Write-Ok    { param($msg) Write-Host "[OK]    $msg" -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Err   { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }

function Get-Arch {
    if ([Environment]::Is64BitOperatingSystem) {
        if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") { return "arm64" }
        return "amd64"
    }
    Write-Err "Butuh Windows 64-bit"
}

function Get-LatestVersion {
    $uri = "https://api.github.com/repos/$Repo/releases/latest"
    $release = Invoke-RestMethod -Uri $uri -Headers @{ "User-Agent" = "whatsar-installer" }
    return $release.tag_name
}

function Install-Binary {
    param([string]$Ver, [string]$Arch)

    $assetName = "whatsar_${Ver}_windows_${Arch}.zip"
    $url = "https://github.com/$Repo/releases/download/$Ver/$assetName"

    Write-Info "Download whatsar $Ver ($Arch)..."
    Write-Info "URL: $url"

    $tmp = Join-Path $env:TEMP "whatsar-install"
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    $zip = Join-Path $tmp "whatsar.zip"

    Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
    Expand-Archive -Path $zip -DestinationPath $tmp -Force

    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    Copy-Item (Join-Path $tmp "whatsar.exe") (Join-Path $InstallDir "whatsar.exe") -Force
    Remove-Item $tmp -Recurse -Force

    Write-Ok "Binary → $InstallDir\whatsar.exe"
}

function New-Config {
    $apiKey    = [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Max 256 }))
    $adminPass = [Convert]::ToBase64String((1..16 | ForEach-Object { Get-Random -Max 256 }))

    $configDir = Join-Path $InstallDir "config"
    $dataDir   = Join-Path $InstallDir "data"
    $logsDir   = Join-Path $InstallDir "logs"

    @($configDir, $dataDir, $logsDir) | ForEach-Object {
        New-Item -ItemType Directory -Force -Path $_ | Out-Null
    }

    $configPath = Join-Path $configDir "config.yaml"
    if (Test-Path $configPath) {
        Write-Warn "Config sudah ada, skip generate"
        return
    }

    @"
# Whatsar config — generated by install.ps1
server:
  port: $Port
  host: "127.0.0.1"

database:
  path: "$($dataDir -replace '\\','/')/whatsar.db"

auth:
  api_key: "$apiKey"
  admin_password: "$adminPass"

sessions:
  max_active: 2

log:
  level: "info"
  file: "$($logsDir -replace '\\','/')/whatsar.log"
"@ | Set-Content -Path $configPath -Encoding UTF8

    @"
API_KEY=$apiKey
ADMIN_PASSWORD=$adminPass
"@ | Set-Content -Path (Join-Path $configDir ".credentials") -Encoding UTF8

    Write-Ok "Config → $configPath"
    return @{ ApiKey = $apiKey; AdminPass = $adminPass }
}

function Install-Service {
    $exe    = Join-Path $InstallDir "whatsar.exe"
    $config = Join-Path $InstallDir "config\config.yaml"
    $svcName = "Whatsar"

    if ($NoService) {
        Write-Warn "Skip Windows Service — jalankan manual: $exe --config $config"
        return
    }

    # Hapus service lama jika ada
    $existing = Get-Service -Name $svcName -ErrorAction SilentlyContinue
    if ($existing) {
        Stop-Service $svcName -Force -ErrorAction SilentlyContinue
        sc.exe delete $svcName | Out-Null
        Start-Sleep -Seconds 2
    }

    $binPath = "`"$exe`" --config `"$config`""
    New-Service -Name $svcName `
        -BinaryPathName $binPath `
        -DisplayName "Whatsar WhatsApp API" `
        -Description "Self-hosted WhatsApp API gateway" `
        -StartupType Automatic | Out-Null

    Start-Service $svcName
    Write-Ok "Windows Service '$svcName' aktif"
}

function Install-Cloudflared {
    if (-not $WithTunnel) { return }

    Write-Info "Install Cloudflare Tunnel..."

    if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
        $arch = if ((Get-Arch) -eq "arm64") { "arm64" } else { "amd64" }
        $url  = "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-$arch.exe"
        Invoke-WebRequest -Uri $url -OutFile "C:\Windows\System32\cloudflared.exe" -UseBasicParsing
    }

    Write-Warn "Setup tunnel manual: cloudflared tunnel login"
    Write-Warn "Lalu: cloudflared tunnel --no-autoupdate run --token YOUR_TOKEN"
}

# ─── Main ─────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "╔══════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║   Whatsar Installer (Windows)      ║" -ForegroundColor Blue
Write-Host "╚══════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

$arch = Get-Arch
Write-Info "Arch: $arch"
Write-Info "Install dir: $InstallDir"

$ver = if ($Version -eq "latest") { Get-LatestVersion } else { $Version }
Install-Binary -Ver $ver -Arch $arch
$creds = New-Config
Install-Service
Install-Cloudflared

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║              Whatsar berhasil terinstall!                ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  URL lokal  : http://127.0.0.1:$Port"
Write-Host "  Admin UI   : http://127.0.0.1:$Port/admin"
Write-Host "  API base   : http://127.0.0.1:$Port/api/v1"
Write-Host ""
Write-Host "  API Key    : $($creds.ApiKey)"
Write-Host "  Admin pass : $($creds.AdminPass)"
Write-Host ""
Write-Host "  Service    : Get-Service Whatsar"
Write-Host "  Log        : $($InstallDir)\logs\whatsar.log"
Write-Host ""
Write-Warn "Simpan API Key & admin password — tidak ditampilkan lagi!"
Write-Host ""