#!/usr/bin/env bash
# User, dirs, .env, systemd, logrotate

setup_user() {
    if ! id "$SERVICE_USER" &>/dev/null; then
        info "Buat user sistem: ${SERVICE_USER}"
        useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
    fi
    ok "User ${SERVICE_USER} OK"
}

setup_dirs() {
    info "Setup direktori ${INSTALL_DIR}..."
    mkdir -p "${INSTALL_DIR}"/{data,logs}
    chown -R "${SERVICE_USER}:${SERVICE_USER}" "${INSTALL_DIR}"
    chmod 750 "${INSTALL_DIR}"
    chmod 700 "${INSTALL_DIR}/data"
    ok "Direktori OK"
}

generate_env() {
    local env_file="${INSTALL_DIR}/.env"
    local cred_file="${INSTALL_DIR}/.credentials"

    if [[ -f "$env_file" ]]; then
        warn ".env sudah ada, skip generate"
        return
    fi

    local api_key admin_pass
    api_key="$(rand_hex 32)"
    admin_pass="$(rand_pass)"

    cat > "$env_file" <<EOF
# Whatsar — generated by install.sh
WHATSAR_HOST=127.0.0.1
WHATSAR_PORT=${PORT}
WHATSAR_DB_PATH=${INSTALL_DIR}/data/whatsar.db
WHATSAR_API_KEY=${api_key}
WHATSAR_ADMIN_PASSWORD=${admin_pass}
WHATSAR_MAX_SESSIONS=2
WHATSAR_LOG_LEVEL=info
# WHATSAR_PUBLIC_URL=https://whatsar.example.com
EOF

    cat > "$cred_file" <<EOF
API_KEY=${api_key}
ADMIN_PASSWORD=${admin_pass}
EOF

    chown "${SERVICE_USER}:${SERVICE_USER}" "$env_file" "$cred_file"
    chmod 600 "$env_file" "$cred_file"

    ok ".env generated → ${env_file}"
}

download_binary() {
    local ver="$1"
    ver="$(release_version "$ver")" || error "Gagal ambil versi release dari GitHub"

    local asset url tmp
    asset="$(release_asset_name "$ver" linux "$ARCH")"
    url="https://github.com/${REPO}/releases/download/${ver}/${asset}.tar.gz"

    info "Download ${BINARY_NAME} ${ver} (${ARCH})..."
    info "URL: ${url}"

    tmp="$(mktemp -d)"
    curl -fsSL "$url" -o "${tmp}/pkg.tar.gz" \
        || error "Download gagal. Release ${ver} untuk linux/${ARCH} belum ada — buat tag v* di GitHub dulu"

    tar -xzf "${tmp}/pkg.tar.gz" -C "${tmp}"
    install -m 755 "${tmp}/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
    chown "${SERVICE_USER}:${SERVICE_USER}" "${INSTALL_DIR}/${BINARY_NAME}"
    rm -rf "${tmp}"

    ok "Binary → ${INSTALL_DIR}/${BINARY_NAME}"
}

setup_swap() {
    if [[ "${SETUP_SWAP:-false}" != "true" ]]; then return; fi
    if swapon --show 2>/dev/null | grep -q '/swapfile'; then
        ok "Swap sudah aktif"
        return
    fi

    info "Setup swap 512MB..."
    fallocate -l 512M /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=512 status=none
    chmod 600 /swapfile
    mkswap /swapfile >/dev/null
    swapon /swapfile

    if ! grep -q '/swapfile' /etc/fstab; then
        echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi
    ok "Swap 512MB aktif"
}

setup_logrotate() {
    info "Setup logrotate..."
    cat > /etc/logrotate.d/whatsar <<EOF
${INSTALL_DIR}/logs/*.log {
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
EOF
    ok "Logrotate → /etc/logrotate.d/whatsar"
}

setup_systemd() {
    if [[ "${SKIP_SYSTEMD:-false}" == "true" ]]; then
        warn "Skip systemd — jalankan: WHATSAR_ENV_FILE=${INSTALL_DIR}/.env ${INSTALL_DIR}/${BINARY_NAME}"
        return
    fi

    info "Setup systemd service..."

    cat > /etc/systemd/system/whatsar.service <<EOF
[Unit]
Description=Whatsar WhatsApp API
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=${INSTALL_DIR}/${BINARY_NAME}
Restart=on-failure
RestartSec=10
LimitNOFILE=65536

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${INSTALL_DIR}/data ${INSTALL_DIR}/logs
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable whatsar
    systemctl restart whatsar
    ok "Service whatsar aktif (systemctl status whatsar)"
}

print_summary() {
    # shellcheck source=/dev/null
    source "${INSTALL_DIR}/.credentials" 2>/dev/null || true

    echo ""
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║              Whatsar berhasil terinstall!                ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo ""
    echo "  URL lokal  : http://127.0.0.1:${PORT}"
    echo "  Admin UI   : http://127.0.0.1:${PORT}/admin"
    echo "  API base   : http://127.0.0.1:${PORT}/api/v1"
    echo "  Health     : http://127.0.0.1:${PORT}/health"
    echo ""
    echo "  API Key    : ${API_KEY:-<lihat ${INSTALL_DIR}/.credentials>}"
    echo "  Admin pass : ${ADMIN_PASSWORD:-<lihat ${INSTALL_DIR}/.credentials>}"
    echo ""
    echo "  Status     : systemctl status whatsar"
    echo "  Log        : journalctl -u whatsar -f"
    echo ""
    warn "Simpan API Key & admin password — tidak ditampilkan lagi!"
    echo ""
}